# Generated by Django 2.0.3 on 2018-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmailt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gmailt3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gmail',
            new_name='Gmailt1',
        ),
    ]
